image:
    - Visual Studio 2019
    - Visual Studio 2017
    - Visual Studio 2015

init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc.ublox.commsdsl
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    matrix:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2015
          CPP_STD: 17 
        - image: Visual Studio 2015
          CPP_STD: 20    
        - image: Visual Studio 2017
          CPP_STD: 20                           
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin

build_script:
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - mkdir %BUILD_DIR%
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="%BOOST_DIR%" -DBoost_USE_STATIC_LIBS=ON 
    - nmake
    - mkdir output.build
    - cd output.build
    - echo ------------------------- Building Output -------------------------
    - cmake ../output -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DOPT_QT_DIR=%QTDIR% -DCMAKE_CXX_STANDARD=%CPP_STD% -DOPT_BUILD_TEST=ON -DOPT_TEST_INPUT_MESSAGES=ublox::input::Ublox5Messages -DOPT_BUILD_PLUGIN=ON -DCMAKE_INSTALL_PREFIX=install
    - nmake all_messages
    - nmake ublox_input_test
    


